_all_lang = {
en:{
    "str001": "English",
    "str002": "Chinese",
    "str003": "Japanese",
    "str004": "Red",
    "str005": "Blue",
    "str006": "Green",
    "str007": "Yellow",
    "str008": "Orange",
    "str009": "Purple",
    "str010": "Xizhi District is a good place in New Taipei city. Keelung river split Xizhi, two highway and railway, drive or take train to anywhere is easily.",
    "str011": "In Xizhi dist., major industries is information and electronic technology, most popular 3C brands like Acer, Garmin headquarters build at Xizhi.",
    "str012": "If you travel to Taipei and take train to Jiufen or Keelung or sky lantern in Shifen, you will passing through Xizhi dist.",
    "str013": "Xike is a train station in Xizhi and service for all commuter of Xizhi Science and Technology Park. It is the biggest simple commute station in Taiwan, every day with 17000+ people take train here.",
    "str014": "This page use v-html to bind text with inside hyperlink tag.",
    "str015": "<h2>In Taiwan</h2>, if you want search <span style=\"color:green;font-weight:700;\">MRT and train</span> take time, you can use <a href=\"https://melixyen.github.io/railtime/\" target=\"_blank\">This Web App</a> to find starting / ending point transfer easily.",
    "str016": "Sure, If you want take bus or tell somebody bus stop information, you can find bus stop time with <a href=\"https://melixyen.github.io/railtime/busp.html\" target=\"_blank\">Bus smart stop creator</a> and make a smart link save in bookmark or share QR Code to other people.",
    "str017": "VueDuoGuo is a multi language solution for old ES5 web site. If you are only use Vue.js without Vuex, Vue-Router or other plugin, and string file load by HTML script src, you can easily use VueDuoGuo to control change language action.",
    "str018": "Inclue this file after Vue.js, call VueDuoGuo.setConfig function and send a config object. When user want change language, call Vue.duoguo.change(key), key is language value by your definition.",
    "str019": "DuoGuo means multiple country in Chinese, usually refers to multi language in web design. So VueDuoGuo mean `Support multi language in Vue.js` and especially for ES5 developer, because many web site only upgrade from jQuery UI to Vue without Vuex to manage data store.",
    "str020": "Demo site of VueDuoGo.",
    "str021": "Now change to English page.",
    "str022": "This page use VueDuoGuo for HTML form.",
    "str023": "Please input something.",
    "str024": "HTML Select Option 1",
    "str025": "HTML Select Option 2",
    "str026": "HTML Select Option 3",
    "str027": "some string in this page only with English version and without others, setConfig baseLang:xxx will load English first and combine to main language.",
    "str028": "I only with English version, now you see me in an English word.",
    "str029": "I have multi language translated, so now I am English.",
    "str030": "Sorry maybe the translator forgot me last night.",
    "str031": "Do you know what is baseLang now ?",
    "str032": "This site help you to check every component change language by click 3 top buttons. The color box also can be clicked, you can see more language change action.",
    "str033": "This page use {type} format string."
},
cht:{
    "str001": "英文",
    "str002": "中文",
    "str003": "日文",
    "str004": "紅色",
    "str005": "藍色",
    "str006": "綠色",
    "str007": "黃色",
    "str008": "橘色",
    "str009": "紫色",
    "str010": "汐止是新北市的一個好所在，基隆河分割汐止，兩條高速公路與火車經過，開車或搭車都很方便。",
    "str011": "汐止主要的產業是資訊與電子科技，許多有名的 3C 製造商如宏碁、Garmimn 總部大樓都在汐止。",
    "str012": "如果你到台北旅行，搭火車至九份、基隆或到十分放天燈，你會經過汐止。",
    "str013": "汐科站是汐止科技園區的通勤車站，它是台灣最大的簡易通勤站，每日有超過 17000 人在此站上下車。",
    "str014": "本頁使用 v-html 綁定超連結元件.",
    "str015": "<h2>在台灣</h2>, 如果你要搜尋 <span style=\"color:green;font-weight:700;\">捷運及火車</span>搭乘時間，您可使用 <a href=\"https://melixyen.github.io/railtime/\" target=\"_blank\">這支 Web App</a> 尋找起點至目的地方便轉乘。",
    "str016": "當然，如果您要搭乘公車或告知其他人公車資訊，您可尋找公車站牌動態時間於 <a href=\"https://melixyen.github.io/railtime/busp.html\" target=\"_blank\">公車站牌 QR Code 雲端看板</a> 製作分享連結並儲存在書籤以及分享 QR Code 給其他人掃。",
    "str017": "VueDuoGuo 是一個多國語言套件給舊的 ES5 網頁。當你僅使用 Vue.js 而未使用 Vuex, Vue-Router 或其他套件，並且字串檔透過 HTML script src 載入，你可以輕鬆的透過 VueDuoGuo 控制語系切換動作。",
    "str018": "在 Vue.js 之後載入此檔，呼叫 VueDuoGuo.setConfig function 並傳入一個設定參數物件。當使用者要切換語言時，呼叫 Vue.duoguo.change(key)，key 是您自行定義的語系名稱。",
    "str019": "DuoGuo 中文多國之意思，在網頁設計上多指多國語言。故 VueDuoGuo 意為 `讓 Vue.js 支援多國語系` 並易於用在 ES5 開發者，因為許多網站升級自 jQuery UI 至 Vue 而未使用 Vuex 管理資料流。",
    "str020": "VueDuoGo 展示網站",
    "str021": "現在切換到中文頁面。",
    "str022": "本頁將 VueDuoGuo 應用於 HTML 表單元件。",
    "str023": "請輸入一些文字",
    "str024": "HTML 下拉選單 1",
    "str025": "HTML 下拉選單 2",
    "str026": "HTML 下拉選單 3",
    "str027": "某些字串在本頁只有英文版本無翻譯其他語言，setConfig baseLang:xxx 將載入先載入英文再結合目標語言填補缺失字串。",
    "str029": "我有翻譯多國語言，所以我現在是中文。",
    "str031": "你知道什麼是 baseLang 了嗎？",
    "str032": "本頁示範所有元件透過三個語言按鈕切換語言檔時的表現。顏色方塊也可以按，您可觀察更多種切換語言時的動作。",
    "str033": "本頁使用 {type} 格式字串。"
},
jp:{
    "str001": "英語",
    "str002": "中国語",
    "str003": "日本語",
    "str004": "赤",
    "str005": "青",
    "str006": "緑",
    "str007": "黄",
    "str008": "橙",
    "str009": "紫",
    "str010": "汐止町は新北市の良い場所です。 基隆川分割西路、2つの高速道路と鉄道、ドライブまたはどこにでも電車に乗るのは簡単です。",
    "str011": "汐止で、主な産業は情報と電子技術、Acerや, Garminはような最も人気のある3Cブランド、本社は汐止で構築しています。",
    "str012": "台北に旅行し、九份、基隆、または十分のスカイランタンに電車で行く場合は、汐止を通過します。",
    "str013": "汐科は汐止の駅で、汐止 科学技術パークの通勤者全員にサービスを提供しています。 ここは台湾で最大のシンプルな通勤駅で、毎日17000人以上が通勤しています。",
    "str014": "このページでは、テキストをハイパーリンクタグの内側にバインドするためにv-htmlを使用しています。",
    "str015": "<h2>台湾で</h2>, <span style=\"color:green;font-weight:700;\">地下鉄や電車</span>で検索したい場合, あなたが簡単に転送は<a href=\"https://melixyen.github.io/railtime/\" target=\"_blank\">この Web App</a>で使用する",
    "str016": "確かに、バスに乗るか、誰かにバス停情報を伝えたいのなら、バス停の時間がわかりますなら <a href=\"https://melixyen.github.io/railtime/busp.html\" target=\"_blank\">Bus smart stop creator</a> またスマートリンクをブックマークに保存するか、他の人とQRコードを共有する.",
    "str017": "VueDuoGuoは、古いES5 Webサイト用の多言語ソリューションです。 Vuex、Vue-Routerまたは他のプラグインなしでVue.jsを使用し、HTMLスクリプトsrcで文字列ファイルをロードするだけであれば、VueDuoGuoを使用して言語の変更アクションを簡単に制御できます。",
    "str018": "このファイルをVue.jsの後に挿入し、VueDuoGuo.setConfig関数を呼び出して構成オブジェクトを送信します。 ユーザーが言語を変更したいときは、Vue.duoguo.change（key）を呼び出してください。keyはあなたの定義による言語の値です。",
    "str019": "DuoGuoは中国語で複数の国を意味し、通常はWebデザインで多言語を指します。 そのため、VueDuoGuoは「Vue.jsで多言語をサポートする」という意味で、特にES5開発者にとっては、データストアを管理するためにVuexを使用せずにjQuery UIからVueにアップグレードするだけであるためです。",
    "str020": "VueDuoGoのデモサイト。",
    "str021": "今すぐ日本語のページに変更します。",
    "str022": "このページはHTMLフォームにVueDuoGuoを使用しています。",
    "str023": "何か入力してください。",
    "str024": "HTML オプションを選択 1",
    "str025": "HTML オプションを選択 2",
    "str026": "HTML オプションを選択 3",
    "str027": "このページの一部の文字列は英語版のみで他の文字列はありません。setConfig baseLang：xxxは最初に英語を読み込み、主言語に結合します。",
    "str029": "私は多言語翻訳されているので、今私は日本語です。",
    "str031": "あなたは今baseLangが何であるか知っていますか？",
    "str032": "このサイトはあなたが3つの一番上のボタンをクリックすることによってあなたがすべてのコンポーネント変更言語をチェックするのを助けます。 カラーボックスもクリックすることができます、あなたはより多くの言語変更アクションを見ることができます。",
    "str033": "このページでは、 {type} フォーマット文字を使用しています。"
}
}