_LANG = {
    "str001": "英文",
    "str002": "中文",
    "str003": "日文",
    "str004": "紅色",
    "str005": "藍色",
    "str006": "綠色",
    "str007": "黃色",
    "str008": "橘色",
    "str009": "紫色",
    "str010": "汐止是新北市的一個好所在，基隆河分割汐止，兩條高速公路與火車經過，開車或搭車都很方便。",
    "str011": "汐止主要的產業是資訊與電子科技，許多有名的 3C 製造商如宏碁、Garmimn 總部大樓都在汐止。",
    "str012": "如果你到台北旅行，搭火車至九份、基隆或到十分放天燈，你會經過汐止。",
    "str013": "汐科站是汐止科技園區的通勤車站，它是台灣最大的簡易通勤站，每日有超過 17000 人在此站上下車。",
    "str014": "本頁使用 v-html 綁定超連結元件.",
    "str015": "<h2>在台灣</h2>, 如果你要搜尋 <span style=\"color:green;font-weight:700;\">捷運及火車</span>搭乘時間，您可使用 <a href=\"https://melixyen.github.io/railtime/\" target=\"_blank\">這支 Web App</a> 尋找起點至目的地方便轉乘。",
    "str016": "當然，如果您要搭乘公車或告知其他人公車資訊，您可尋找公車站牌動態時間於 <a href=\"https://melixyen.github.io/railtime/busp.html\" target=\"_blank\">公車站牌 QR Code 雲端看板</a> 製作分享連結並儲存在書籤以及分享 QR Code 給其他人掃。",
    "str017": "VueDuoGuo 是一個多國語言套件給舊的 ES5 網頁。當你僅使用 Vue.js 而未使用 Vuex, Vue-Router 或其他套件，並且字串檔透過 HTML script src 載入，你可以輕鬆的透過 VueDuoGuo 控制語系切換動作。",
    "str018": "在 Vue.js 之後載入此檔，呼叫 VueDuoGuo.setConfig function 並傳入一個設定參數物件。當使用者要切換語言時，呼叫 Vue.duoguo.change(key)，key 是您自行定義的語系名稱。",
    "str019": "DuoGuo 中文多國之意思，在網頁設計上多指多國語言。故 VueDuoGuo 意為 `讓 Vue.js 支援多國語系` 並易於用在 ES5 開發者，因為許多網站升級自 jQuery UI 至 Vue 而未使用 Vuex 管理資料流。",
    "str020": "VueDuoGo 展示網站",
    "str021": "現在切換到中文頁面。",
    "str022": "本頁將 VueDuoGuo 應用於 HTML 表單元件。",
    "str023": "請輸入一些文字",
    "str024": "HTML 下拉選單 1",
    "str025": "HTML 下拉選單 2",
    "str026": "HTML 下拉選單 3",
    "str027": "某些字串在本頁只有英文版本無翻譯其他語言，setConfig baseLang:xxx 將載入先載入英文再結合目標語言填補缺失字串。",
    "str029": "我有翻譯多國語言，所以我現在是中文。",
    "str031": "你知道什麼是 baseLang 了嗎？",
    "str032": "本頁示範所有元件透過三個語言按鈕切換語言檔時的表現。顏色方塊也可以按，您可觀察更多種切換語言時的動作。",
    "str033": "本頁使用 {type} 格式字串。"
}